#include<iostream>
using namespace std;
main()
{
 cout << "Number 1: ";
 int no1;
 cin >> no1;
 cout << "Number 2: ";
 int no2;
 cin >> no2;
 cout << "Number 3: ";
 int no3;
 cin >> no3;
 cout << "Number 4: ";
 int no4;
 cin >> no4;
 cout << "Number 5: ";
 int no5;
 cin >> no5;
 cout << "Number 6: ";
 int no6;
 cin >> no6;
 cout <<"Number 7: ";
 int no7;
 cin >> no7;
 cout << "Number 8: ";
 int no8;
 cin >> no8;
 cout << "Number 9: ";
 int no9;
 cin >> no9;
 cout << "Number 10: ";
 int no10;
 cin >> no10;
 cout << "Number 11: ";
 int no11;
 cin >> no11;
 cout <<"Number 12: ";
 int no12;
 cin >> no12;
 cout << "Number 13: ";
 int no13;
 cin >> no13;
 cout << "Number 14: ";
 int no14;
 cin >> no14;
 cout << "Number 15: ";
 int no15;
 cin >> no15;
 int result1;
 result1=no1+no2+no3+no4+no5;
 int result2;
 result2=no6*no7*no8*no9*no10;
 int result3;
 result3=no11-no12-no13-no14-no15;
 int result4;
 result4=result1+result2;
 int result5;
 result5=result4-result3;
 cout << "The final result is: " << result5;
}